name: CI/CD to OCI VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Upload app to temporary folder
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./"
        target: "/home/${{ secrets.VM_USERNAME }}/app-temp"
        strip_components: 0

    - name: Move files & restart PM2 with sudo
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            sudo bash -c '
            rm -rf ${{ secrets.APP_PATH }}/*
            cp -r /home/${{ secrets.VM_USERNAME }}/app-temp/* ${{ secrets.APP_PATH }}/
            chown -R www-data:www-data ${{ secrets.APP_PATH }}
            rm -rf /home/${{ secrets.VM_USERNAME }}/app-temp
            cd ${{ secrets.APP_PATH }}
            pm2 restart ${{ secrets.PM2_APP_NAME }}
          
